version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: liveorder-db
    environment:
      - POSTGRES_USER=Swatiai11414
      - POSTGRES_PASSWORD=Swatiai@@@###2003
      - POSTGRES_DB=hdos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Swatiai11414 -d hdos"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
